wandb_version: 1

num_envs:
  desc: null
  value: 2
timesteps_per_env:
  desc: null
  value: 1000
nb_episodes:
  desc: null
  value: 50
render_mode:
  desc: null
  value: human
verbose:
  desc: null
  value: true
save_model:
  desc: null
  value: false
log_type:
  desc: null
  value: test
env:
  desc: null
  value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at
    0x000001D2C3576730>
device:
  desc: null
  value: cuda
tensorboard_log:
  desc: null
  value: ./logs/test/2023-11-18_12-17-00/
n_steps:
  desc: null
  value: 1000
batch_size:
  desc: null
  value: 2000
_wandb:
  desc: null
  value:
    python_version: 3.8.8
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700327844.031703
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.8.8
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
